-- Revert the AI-generated fundamentals seed batch from migrations 0013 and 0014.
-- These rows were inserted without production data access and contain judgement scores.
-- Match by the seed batch source URLs instead of symbol alone to avoid broad deletion.
DELETE FROM "miner_fundamentals"
WHERE "source_url" IN (
  'https://firstmajestic.com/investors/news-releases/first-majestic-announces-q2-2026-financial-results-and-quarterly-dividend-payment',
  'https://www.andeansilver.com/cerro-bayo-project/',
  'https://www.avino.com/news/avino-announces-q2-2026-production-results',
  'https://ayagoldsilver.com/news/news-releases/aya-gold--silver-reports-q2-2026-results-and-delivers-record-operational-performance',
  'https://bannermanenergy.com/project-economics/',
  'https://www.cameco.com/invest/financial-information/quarterly-reports/2026/q2',
  'https://www.coeur.com/investors/news/news-details/2026/Coeur-Reports-Second-Quarter-2026-Results/default.aspx',
  'https://deepyellow.com.au/projects/namibia/tumas-project/',
  'https://www.globalxetfs.com.au/funds/',
  'https://www.vaneck.com/us/en/investments/gold-miners-etf-gdx/overview/?redirectVE=generic',
  'https://www.hecla.com/investors/why-hecla',
  'https://www.kinross.com/English/news-and-investors/news-releases/press-release-details/2026/Kinross-reports-strong-2026-second-quarter-results/default.aspx',
  'https://panamericansilver.com/operations/silver-segment/juanicipio/',
  'https://investors.newmont.com/investors/news-release/news-details/2026/Newmont-Reports-2025-Mineral-Reserves-of-118-2-Million-Gold-Ounces-and-12.5-Million-Tonnes-of-Copper/default.aspx',
  'https://financialfilings.com/filings/northern-star-resources-ltd/annual-report/2026/56809935/',
  'https://www.sec.gov/Archives/edgar/data/1698535/000106299326002332/exhibit99-2.htm',
  'https://panamericansilver.com/news/pan-american-silver-reports-second-quarter-2026-financial-results/',
  'https://www.globenewswire.com/news-release/2026/07/22/3331046/0/en/Paladin-Energy-Ltd-Quarterly-Report-for-the-period-ending-30-June-2026.html',
  'https://financialfilings.com/filings/regis-resources-limited/earnings-release/2026/57059685/',
  'https://www.globalxetfs.com/funds/sil?source_caller=ui',
  'https://amplifyetfs.com/silj/',
  'https://www.sec.gov/Archives/edgar/data/1340677/000110465926066826/tm2615713d1_ex99-4.htm',
  'https://www.betashares.com.au/fund/global-uranium-etf/',
  'https://investors.energyfuels.com/2026-08-05-Energy-Fuels-Announces-Q2-2026-Results',
  'https://www.vaultminerals.com/operations/leonora-operations',
  'https://www.westerncopperandgold.com/casino-project/',
  'https://www.globalxetfs.com.au/funds/atom/',
  'https://www.barrick.com/English/news/news-details/2026/q2-2026-results/default.aspx',
  'https://denisonmines.com/projects/wheeler-river-project/phoenix/',
  'https://www.sec.gov/Archives/edgar/data/1277866/000117184326005027/exh_991.htm',
  'https://encore.mediaroom.com/2026-08-13-enCore-Energy-Reports-Q2-2026-Financial-Results',
  'https://www.investegate.co.uk/announcement/rns/greatland-gold--ggp/june-2026-quarterly-activities-report-/9692219',
  'https://www.heliostarmetals.com/news-media/news-releases/heliostar-presents-q2-2026-financial-and-operating-results-with-record-gold-production-and-cash-balance',
  'https://laramide.com/laramide-resources-announces-updated-preliminary-e-15357/',
  'https://www.rangeetfs.com/nukz?trk=public_post-text',
  'https://www.nasdaq.com/press-release/santacruz-silver-reports-second-quarter-2026-financial-results-2026-08-17',
  'https://www.globalxetfs.com.au/funds/slvm/',
  'https://sprott.com/investment-strategies/exchange-listed-products/physical-commodity-funds/uranium/',
  'https://www.globalxetfs.com/funds/ura/'
);
