import type { MinerFundamentalsInput } from "@/lib/storage";

export const starterMinerFundamentals: MinerFundamentalsInput[] = [
  {
    symbol: "CDE",
    name: "Coeur Mining Inc.",
    primaryMetal: "Silver / gold",
    jurisdiction: "United States, Mexico, Canada",
    projectStage: "Producer",
    productionOz: 17900000,
    aiscUsdPerOz: null,
    resourceMoz: 313.8,
    reserveMoz: 274.4,
    cashAud: null,
    debtAud: null,
    marketCapAud: null,
    npvAud: null,
    capexAud: null,
    irrPercent: null,
    jurisdictionScore: 4,
    balanceSheetScore: 4,
    dilutionScore: 3,
    managementScore: 3,
    notes: "Company-reported 2025 silver production, silver reserves and measured/indicated plus inferred silver resources. Scores are SouthernStar judgement inputs, not company-reported metrics.",
    sourceUrl: "https://www.sec.gov/Archives/edgar/data/215466/000021546626000004/cde-20251231.htm",
    asOfDate: "2025-12-31",
  },
  {
    symbol: "AYA",
    name: "Aya Gold & Silver Inc.",
    primaryMetal: "Silver",
    jurisdiction: "Morocco",
    projectStage: "Producer / expansion",
    productionOz: 5000000,
    aiscUsdPerOz: null,
    resourceMoz: 104.75,
    reserveMoz: 73.39,
    cashAud: null,
    debtAud: null,
    marketCapAud: null,
    npvAud: null,
    capexAud: null,
    irrPercent: null,
    jurisdictionScore: 3,
    balanceSheetScore: 4,
    dilutionScore: 3,
    managementScore: 3,
    notes: "Company-reported 2025 silver production and Zgounder reserve/resource base. Financial fields are left blank where the source reports non-AUD figures.",
    sourceUrl: "https://www.sec.gov/Archives/edgar/data/1826836/000162828026024772/exhibit99103-annualmdaxdat.htm",
    asOfDate: "2025-12-31",
  },
  {
    symbol: "ASL",
    name: "Andean Silver Limited",
    primaryMetal: "Silver / gold",
    jurisdiction: "Chile",
    projectStage: "Developer / explorer",
    productionOz: null,
    aiscUsdPerOz: null,
    resourceMoz: 136,
    reserveMoz: null,
    cashAud: null,
    debtAud: null,
    marketCapAud: null,
    npvAud: null,
    capexAud: null,
    irrPercent: null,
    jurisdictionScore: 4,
    balanceSheetScore: 3,
    dilutionScore: 2,
    managementScore: 3,
    notes: "Company-reported Cerro Bayo silver-equivalent mineral resource as at 30 June 2026. Developer-stage record intentionally leaves production, AISC and reserve fields blank.",
    sourceUrl: "https://www.andeansilver.com/cerro-bayo-project/",
    asOfDate: "2026-06-30",
  },
];
